---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: save username 
    command: whoami
    become: false
    register: username
    ignore_errors: true

  - name: update, upgrade & autoremove 
    command: apt update && apt upgrade && apt autoremove
    
  - name: install packages
    package: 
      name: 
        - copyq
        - adb
        - awscli
        - curl
        - gzip
        - whois
        - photoflare
        - openjdk-11-jdk
        - fzf
        - guake
        - docker.io
        - nmap
        - nodejs
        - npm
        - python3-pip
        - python3
        - rclone
        - vagrant
        - snapd
        - virtualbox
        - net-tools
        - ffmpeg
    async: 60
  
  - name: downloading chrome .deb file
    command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: installing chrome file
    command: dpkg -i google-chrome-stable_current_amd64.deb

  - name: installing nvm
    command: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh

  - name: install spotify using snap 
    command: snap install spotify 
    ignore_errors: yes

  - name: install ngrok using snap 
    command: snap install ngrok  
    ignore_errors: yes

  - name: install oneNote snap 
    command: snap install p3x-onenote 
    ignore_errors: yes

  - name: install keepassxc using snap 
    command: snap install keepassxc
    ignore_errors: yes
  
  - name: install vscode using snap 
    command: snap install code --classic 
    ignore_errors: yes
    
  - name: install notepad++ using snap 
    command: snap install notepad-plus-plus
    ignore_errors: yes
    
  - name: add OBS repo 
    command: add-apt-repository ppa:obsproject/obs-studio
    ignore_errors: yes
    
  - name: installing OBS studio 
    command: apt install obs-studio -y 
    ignore_errors: yes
    
  - name: installing VLC media player
    command: snap install vlc
    ignore_errors: yes

  - name: installing libreoffice
    command: snap install libreoffice
    ignore_errors: yes

  - name: installing slack
    command: snap install slack
    ignore_errors: yes

  - name: installing postman
    command: snap install postman
    ignore_errors: yes

  - name: Create autostart directory
    file:
      path: /home/{{ username.stdout }}/.config/autostart
      state: directory

  - name: Set Startup applications
    file:
      state: link
      force: yes
      src: "/usr/share/applications/{{ item }}"
      dest: /home/{{ username.stdout }}/.config/autostart/{{ item }}
    with_items:
      - com.github.hluk.copyq.desktop
      - ferdi.desktop
      - guake.desktop
