---
- hosts: localhost
  connection: local
  become: true


  tasks:
  - name: install packages
    package: 
      name: 
        - htop
        - copyq
        - fzf
        - guake
        - docker.io
        - nmap
        - nodejs
        - npm
        - openjdk-14-jre
        - python3-pip
        - python3
        - rclone
        - vagrant
        - snapd
  
  - name: downloading chrome .deb file
    command: wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

  - name: installing chrome file
    command: dpkg -i google-chrome-stable_current_amd64.deb

  - name: install snap packages
    command: snap install spotify ngrok p3x-onenote keepassxc code
    ignore_errors: yes